Repository SCRT-HQ/PSProfile, pull requests merged in 2019-10, with the labels that each got.

#19 !deploy v0.4.1 release
  CHANGELOG.md
  PSProfile/Classes/PSProfile.Classes.ps1
  invoke.build.ps1
Labels: enhancement

#20 !deploy v0.5.0 ready for release
  CHANGELOG.md
  PSProfile/Classes/PSProfile.Classes.ps1
  PSProfile/PSProfile.psd1
  PSProfile/PSProfile.psm1
  invoke.build.ps1
Labels: enhancement

#24 Add WithInsiders switch.
  PSProfile/Public/Power Tools/Open-Code.ps1
Labels: hacktoberfest

#25 Issue21
  PSProfile/Classes/PSProfile.Classes.ps1
Labels: bug, enhancement
